### ISSUE TITLE
Tut should not be a dependency of the released artifact

### ISSUE THREAD

**Issue by granthenke** [fthomas/refined#17]
https://repo1.maven.org/maven2/eu/timepit/refined_2.11/0.0.3/refined_2.11-0.0.3.pom

```
...
<dependency>
<groupId>org.tpolecat</groupId>
<artifactId>tut-core_2.11</artifactId>
<version>0.3.2</version>
</dependency>
...
```

This may be related to https://github.com/tpolecat/tut/issues/36:

**Comment by fthomas** [comment]
Good catch! I see what I can do about it.

**Comment by fthomas** [comment]
This is a known problem: https://gitter.im/tpolecat/tut?at=557b43a8873bcf056fb4e9cb
To use refined right now, you need to add this resolver to your build:

    resolvers += "tpolecat" at "http://dl.bintray.com/tpolecat/maven"

I'll also change the refined build to a multi-project build (which is also required to support Scala.js) to fix this issue, but since I'm going on vacation tomorrow this will take some time.

**Comment by granthenke** [comment]
Thanks for looking into it. No hurry on my part, I just wanted to report it for future releases. I am using Gradle for my build and globally excluded tut as a transitive dependency:

```groovy
configurations {
    compile.exclude module: "tut-core_2.11"
}
```

**Comment by fthomas** [comment]
@granthenke refined 0.1.0 has been released and it does depend on tut-core anymore. Thanks again for reporting this issue!
