### ISSUE TITLE
Dependent refinement types compilation errors

### ISSUE THREAD

**Issue by OleksandrBezhan** [fthomas/refined#319]
I created an example project https://github.com/OleksandrBezhan/refined-issue-example showcasing the following issues with dependent refinement types:

1. Incremental compilation fails. How to reproduce: change file `example.Test.scala` and run `compile`. It fails, but `clean compile` works.
2. Literals don't get refined properly in tests. How to reproduce: `test:compile` and you will get an error:
```
[error] /Users/alex/source/refined/src/test/scala/example/BlindsTest.scala:8:30: type mismatch;
[error]  found   : Long(10L)
[error]  required: Long with shapeless.tag.Tagged[eu.timepit.refined.numeric.Greater[L]]
[error]     Blinds.createLiteral(5L)(10L)
```

I'm not sure maybe I'm using refined in a wrong way. Could you please take a look at example project ?

**Comment by oskoi** [comment]
@fthomas Hi! What do you think about supporting TupleN? This can fix problem with dependent refinement types.

**Comment by fthomas** [comment]
@OleksandrBezhan Thanks for the report! I'll investigate this.
@oskoi Could you elaborate on your idea to support TupleN? I don't quite follow.

**Comment by oskoi** [comment]
@fthomas 
You can create a dependent refinement using Scala's path dependent types and shapeless (Witness) at compile-time. But this leads to problems of incremental compilation as mentioned above. I suggest adding support not only for literal types, but also for TupleN in macros.
For example, instead of 
```scala
def baz[I <: Int](i: Witness.Aux[I])(j: Int Refined Greater[i.T]) = j - i.value
baz(Witness(6))(4)
```
you can do the following
```scala
final case class FstGreaterThanSnd()

implicit val fstGreaterThanSndValidate: Validate.Plain[(Int, Int), Valid] = 
  Validate.fromPredicate(t => t._1 > t._2, t => s"${t._1} is not greater than ${t._2}", FstGreaterThanSnd())

val baz: (Int, Int) Refined FstGreaterThanSnd = (6, 4)
```
What do you think about it ?

**Comment by fthomas** [comment]
@oskoi Yes that makes a lot of sense. Currently refined only supports compile-time refinements of [literals](https://www.scala-lang.org/files/archive/spec/2.11/01-lexical-syntax.html#literals) because it is safe and easy to extract their values from the AST at compile-time. So you are proposing to also allow compile-time refinements of tuples that only contain literals. We would basically expand the notion of literals in the context of refined.

If we are at it, we could also treat `List(1, 2, 3)`, `Map(1 -> (2, 3))`, etc. as "extended literals". At this point, I think it is worth to have a separate macro library that can decide if a tree is an "extended literal" and is able to extract its value. As it happens, I started working on such a library here https://github.com/fthomas/konstant but didn't came very far due to a lack of free time. There is also this [old branch](https://github.com/fthomas/refined/compare/topic/constant-collections) where I tried to treat collections with literals as "extended literals" which again I've stopped working on because of lacking free time.

It would be cool if someone else would pick this idea up. ;-)

**Comment by fthomas** [comment]
@OleksandrBezhan I finally found time to look into this issue. Sorry for taking so long.

I think there is nothing wrong with your code. The culprit seems to be `shapeless.Witness`. If I replace `Long` with `String` and remove `Witness` in `createLiteral` and change `Blinds` accordingly, everything seems to be working fine:
```scala
  def createLiteral[L <: String](sb: L)(bb: String @@ StartsWith[sb.type]): Blinds =
    new Blinds(sb, bb)
```

I also tried it with Typelevel Scala with `-Yliteral-types` (https://github.com/OleksandrBezhan/refined-issue-example/compare/master...fthomas:topic/literal-types) which allows us to use `sb.type` directly even if `sb` is a subtype of `Long` and it worked fine. So it seems that `Witness` is not usable in this case and I'm afraid there is nothing we can do to fix this in refined.

The good news is that SIP-23 was recently accepted and literal types will probably land in Scala 2.13 so that your example should just work then.
