### ISSUE TITLE
How to specify "non empty string with size greater 0 and less then N"?

### ISSUE THREAD

**Issue by vasily-kirichenko** [fthomas/refined#496]
I'm trying this:

```scala
type OrderId = String Refined And[NonEmptyString, FiniteString[W.`50`.T]]
val order: OrderId = "1234UE13"
```

But it does not compile:

```
Error:(30, 25) type mismatch;
 found   : String("1234UE13")
 required: A$A32.A$A32.Domain.OrderId
    (which expands to)  eu.timepit.refined.api.Refined[String,eu.timepit.refined.boolean.And[eu.timepit.refined.api.Refined[String,eu.timepit.refined.boolean.Not[eu.timepit.refined.collection.Empty]],eu.timepit.refined.api.Refined[String,eu.timepit.refined.collection.Size[eu.timepit.refined.boolean.And[eu.timepit.refined.boolean.Not[eu.timepit.refined.numeric.Less[shapeless._0]],eu.timepit.refined.boolean.Not[eu.timepit.refined.numeric.Greater[Int(50)]]]]]]]
  val order: OrderId = "1234UE13"
                       ^
```

**Comment by fthomas** [comment]
Try ``type OrderId = String Refined Size[Interval.Closed[W.`1`.T, W.`50`.T]]``.

`NonEmptyString` is an alias for `String Refined NonEmpty` and `FiniteString[50]` is an alias for `String Refined MaxSize[50]`. The reason why your `OrderId` does not work is because `And` can only combine predicates (like `NonEmpty` and `MaxSize[50]`) and not refined types (like `NonEmptyString` and `FiniteString[50]`). So ``type OrderId = String Refined (NonEmpty And MaxSize[W.`50`.T])`` should work too.

**Comment by vasily-kirichenko** [comment]
Thanks!
