### ISSUE TITLE
Guide for implementing a custom refined type

### ISSUE THREAD

**Issue by henricook** [fthomas/refined#633]
I love this library, thanks for your work on it

I wanted a way to say a FiniteDuration must be > `5 seconds` earlier today and set about looking into writing my own refined type, but it looks tricky - is this really simple, have I missed something?

A guide on extending the library with your own types might be nice (which is why i made this ticket)

**Comment by fthomas** [comment]
It is indeed a bit tricky because you somehow need to lift the predicate `> 5 seconds` to the type-level. The library supports `> 5` for numeric types with ``Greater[W.`5`.T]`` but `FiniteDuration` is a quantity with a unit of measurement and it would be nonsensical to have ``FiniteDuration Refined Greater[W.`5`.T]`` because 5 has no associated unit. If we could express quantities at the type-level we could maybe support something like this: ``FiniteDuration Refined Greater[Quantity[W.`5`.T, Seconds]]``.

A simpler way to support `FiniteDuration` would be to have a higher-order predicate that converts the length to a numeric value with a known unit which is then passed to one of the numeric predicates:  ``FiniteDuration Refined LengthInSeconds[Greater[W.`5`.T]]``

This would be similar to the existing `Size` predicate which allows to refine collections based on their size, for example: ``List[String] Refined Size[Greater[W.`5`.T]]``.

To implement this, you would need to add the predicate and a `Validate` instance for `FiniteDuration` (which would be similar to the [`Validate` instance for `Size`](https://github.com/fthomas/refined/blob/16c39ebf23c2f9e8dc4ca059acb0fd34733546e3/modules/core/shared/src/main/scala/eu/timepit/refined/collection.scala#L255-L275)):
```scala
final case class LengthInSeconds[P](p: P)
object LengthInSeconds {
  implicit def lengthInSecondsValidate[P, RP](
    implicit v: Validate.Aux[Long, P, RP]
  ): Validate.Aux[FiniteDuration, LengthInSeconds[P], LengthInSeconds[v.Res]] =
    // convert FiniteDuration with toSeconds here and use v to validate that value
    ???
}
```

**Comment by henricook** [comment]
This is super useful, thanks!

**Comment by henricook** [comment]
I've done some shameless thievery from the `size` validate instance you linked, and i haven't yet tested this but:

```
final case class LengthInSeconds[P](lengthInSeconds: P)

object LengthInSeconds {
  implicit def lengthInSecondsValidate[P, RP](
    implicit v: Validate.Aux[Long, P, RP]
  ): Validate.Aux[FiniteDuration, LengthInSeconds[P], LengthInSeconds[v.Res]] =
    // convert FiniteDuration with toSeconds here and use v to validate that value
    new Validate[FiniteDuration, LengthInSeconds[P]] {
      override type R = LengthInSeconds[v.Res]

      override def validate(duration: FiniteDuration): Res = {
        val r = v.validate(duration.toSeconds)
        r.as(LengthInSeconds(r))
      }

      override def showExpr(duration: FiniteDuration): String =
        v.showExpr(duration.toSeconds)

      override def showResult(duration: FiniteDuration, r: Res): String = {
        val lengthInSeconds = duration.toSeconds
        val nested          = v.showResult(lengthInSeconds, r.detail.lengthInSeconds)
        Resources.predicateTakingResultDetail(s"lengthInSeconds($duration) = $lengthInSeconds", r, nested)
      }
    }
}
```

**Comment by henricook** [comment]
If I was validating this would I use 
```scala
val minTimeRefinedPredicate = refineV[LengthInSeconds[Greater[W.`5`.T]]](_: FiniteDuration)
``` ?
This currently says:
```
could not find implicit value for parameter v: eu.timepit.refined.api.Validate[scala.concurrent.duration.FiniteDuration,com.my.app.common.validation.CustomRefinedTypes.LengthInSeconds[eu.timepit.refined.numeric.Greater[Int(5)]]]
```

**Comment by fthomas** [comment]
Try to use ``W.`5L`.T`` since the inner validate instance requires a `Long`: `implicit v: Validate.Aux[Long, P, RP]`.

**Comment by henricook** [comment]
Thanks, that would have taken me a million years to find

**Comment by fthomas** [comment]
I'm curious, is this working now?

**Comment by henricook** [comment]
Sure is! I got a bit side tracked today but I was just writing some tests to cover it in my project, but signs look good

On my to-do list is to see if I can save on this repetition: 

```
refineV[LengthInSeconds[Greater[W.`5`.T]]](_: FiniteDuration)
```

Because I have a field in a case class that's 'fieldName: MySpecialType` and `type MySpecialType = FiniteDuration Refined LengthInSeconds[Greater[W.`5`.T]]`

So I kind of have the rules in two places, which seems hard/trickier to maintain

**Comment by fthomas** [comment]
You could define a companion object for `MySpecialType`:
```scala
type MySpecialType = FiniteDuration Refined LengthInSeconds[Greater[W.`5`.T]]

object MySpecialType extends RefinedTypeOps[MySpecialType, FiniteDuration]
```
`MySpecialType.from` is then the same function as ``refineV[LengthInSeconds[Greater[W.`5`.T]]](_: FiniteDuration)``.

**Comment by henricook** [comment]
Amazing, that's me happy - thanks again!
