### ISSUE TITLE
refined is not happly with Int to Double conversion

### ISSUE THREAD

**Issue by OlivierBlanvillain** [fthomas/refined#96]
Do you think the following should work:? (without -Ywarn-numeric-widen)

    scala> def f(d: Double @@ NonNegative) = ()
    f: (d: shapeless.tag.@@[Double,eu.timepit.refined.numeric.NonNegative])Unit

    scala> f(1)
    <console>:30: error: type mismatch;
     found   : Int(1)
     required: shapeless.tag.@@[Double,eu.timepit.refined.numeric.NonNegative]
        (which expands to)  Double with shapeless.tag.Tagged[eu.timepit.refined.boolean.Not[eu.timepit.refined.numeric.Less[shapeless._0]]]
           f(1)
             ^

**Comment by fthomas** [comment]
My first reaction is: Yes, it is probably a good thing that this does not compile. I could imagine that making the above to work could introduce weird behavior in other situations - although I do not yet know how to make it work.

I've to think about this a bit more.

**Comment by OlivierBlanvillain** [comment]
I totally agree with you that it's sane no to get an error here, and since I've learned about `-Ywarn-numeric-widen` I never compile code without it (why is it off by default? Because Java?...). But for end users it might be confusing to be able to call `def f(d: Double): Unit` with an Int, but not `def g(d: Double @@ NonNegative): Unit`.

**Comment by fthomas** [comment]
Numeric widening is specified in the Scala spec [§2.26.1](http://www.scala-lang.org/files/archive/spec/2.11/06-expressions.html#value-conversions) which says that those type conversions happen if there is a [weak conformance relationship](http://www.scala-lang.org/files/archive/spec/2.11/03-types.html#weak-conformance) between the involved types.

Maybe we could support this weak conformance by adding an implicit conversion `T1 => T2` to `RefineM.macroImpl` which allows the base type to vary from `T1` to `T2` but I'm not convinced that this is a good idea. Especially because I think that one should always compile with `-Ywarn-numeric-widen`.

**Comment by fthomas** [comment]
@OlivierBlanvillain I'm going to close this issue for the reasons outlined above and because supporting weak conformance would probably add some complexity to the library which I'd like to avoid in this stage of the library. I'm open to revisit this decision if someone shows me that this can easily done. :-)

**Comment by OlivierBlanvillain** [comment]
Ok, thanks for investigating the issue!
